#!/usr/bin/env bash
set -euo pipefail

# ═══════════════════════════════════════════════════════════════════════════════
# VMflow Update Script
# Pulls latest code, applies new migrations, rebuilds & restarts services.
# Run from the Docker/ directory.
# ═══════════════════════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Parse flags ──────────────────────────────────────────────────────────────
SKIP_FRONTEND=false
for arg in "$@"; do
    case "$arg" in
        --no-frontend) SKIP_FRONTEND=true ;;
        -h|--help)
            echo "Usage: bash update.sh [OPTIONS]"
            echo "  --no-frontend   Skip frontend rebuild"
            exit 0 ;;
    esac
done

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

info()    { echo -e "  ${CYAN}ℹ${NC}  $1"; }
success() { echo -e "  ${GREEN}✔${NC}  $1"; }
warn()    { echo -e "  ${YELLOW}⚠${NC}  $1"; }
error()   { echo -e "  ${RED}✖${NC}  $1"; exit 1; }
step()    { echo; echo -e "${BOLD}═══ $1 ═══${NC}"; echo; }

# ═══════════════════════════════════════════════════════════════════════════════
# Pre-flight checks
# ═══════════════════════════════════════════════════════════════════════════════

[ -f .env ] || error ".env not found. Run setup.sh first."
docker compose ps --services >/dev/null 2>&1 || error "Docker stack is not running. Start it with: docker compose up -d"

# ═══════════════════════════════════════════════════════════════════════════════
# Step 1: Pull latest code
# ═══════════════════════════════════════════════════════════════════════════════
step "1/4 — Pulling Latest Code"

cd "$SCRIPT_DIR/.."

BEFORE=$(git rev-parse HEAD)
git pull --ff-only
AFTER=$(git rev-parse HEAD)

if [ "$BEFORE" = "$AFTER" ]; then
    info "Already up to date (${BEFORE:0:7})"
else
    success "Updated: ${BEFORE:0:7} → ${AFTER:0:7}"
    echo
    git --no-pager log --oneline "${BEFORE}..${AFTER}"
fi

cd "$SCRIPT_DIR"

# ═══════════════════════════════════════════════════════════════════════════════
# Step 1.5: Check for new environment variables
# ═══════════════════════════════════════════════════════════════════════════════
step "Environment Check"

# Read env vars safely (values may contain spaces, so we can't just `source .env`)
while IFS='=' read -r key value; do
    # Skip comments and blank lines
    [[ "$key" =~ ^[[:space:]]*# ]] && continue
    [[ -z "$key" ]] && continue
    # Trim whitespace from key
    key=$(echo "$key" | xargs)
    # Export the variable
    export "$key=$value"
done < .env

# ─── VAPID keys (required for push notifications) ────────────────────────────
if [ -z "${VAPID_PUBLIC_KEY:-}" ] || [ -z "${VAPID_PRIVATE_KEY:-}" ]; then
    info "VAPID keys not found — generating for push notifications..."

    base64url_encode() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

    VAPID_PRIVKEY_PEM=$(openssl ecparam -name prime256v1 -genkey -noout 2>/dev/null)
    VAPID_PRIVATE_KEY=$(echo "$VAPID_PRIVKEY_PEM" | openssl ec -noout -text 2>/dev/null \
      | grep -A3 'priv:' | tail -n+2 | tr -d ' :\n' | xxd -r -p | base64url_encode)
    VAPID_PUBLIC_KEY=$(echo "$VAPID_PRIVKEY_PEM" | openssl ec -pubout -outform DER 2>/dev/null \
      | tail -c 65 | base64url_encode)

    # Extract domain from SITE_URL or SUPABASE_PUBLIC_URL for VAPID_SUBJECT
    DOMAIN_FOR_VAPID=$(echo "${SITE_URL:-${SUPABASE_PUBLIC_URL:-localhost}}" | sed 's|https\{0,1\}://||;s|:.*||;s|^app\.||')
    VAPID_SUBJECT="mailto:admin@${DOMAIN_FOR_VAPID}"

    # Append to Docker/.env
    cat >> .env << VAPIDEOF

##########
# Push Notifications (VAPID)
# Auto-generated by update.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#########

VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
VAPID_SUBJECT=${VAPID_SUBJECT}
VAPIDEOF

    success "VAPID keys generated and appended to .env"

    # Also update management-frontend/.env if it exists
    FRONTEND_ENV="$SCRIPT_DIR/../management-frontend/.env"
    if [ -f "$FRONTEND_ENV" ]; then
        if ! grep -q "VAPID_PUBLIC_KEY" "$FRONTEND_ENV"; then
            echo "VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}" >> "$FRONTEND_ENV"
            success "VAPID_PUBLIC_KEY added to management-frontend/.env"
        fi
    fi
else
    success "VAPID keys present"
fi

# ─── MQTT admin credentials (required for broker auth) ────────────────────────
if [ -z "${MQTT_ADMIN_PASS:-}" ]; then
    info "MQTT admin credentials not found — generating..."

    generate_random() { openssl rand -base64 "$1" 2>/dev/null | tr -d '\n'; }

    MQTT_ADMIN_PASS=$(generate_random 16)

    cat >> .env << MQTTEOF

##########
# MQTT Credentials
# Auto-generated by update.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Devices use hardcoded vmflow/vmflow. Admin is used by forwarder + edge functions.
#########

MQTT_ADMIN_USER=admin
MQTT_ADMIN_PASS=${MQTT_ADMIN_PASS}
MQTTEOF

    # Regenerate mosquitto passwd file
    MQTT_PASSWD_FILE="${SCRIPT_DIR}/mqtt/config/passwd"
    rm -f "$MQTT_PASSWD_FILE"
    touch "$MQTT_PASSWD_FILE"
    docker run --rm -v "${SCRIPT_DIR}/mqtt/config:/mosquitto/config" eclipse-mosquitto:2.1.2-alpine \
      sh -c "
        mosquitto_passwd -b /mosquitto/config/passwd vmflow 'vmflow' && \
        mosquitto_passwd -b /mosquitto/config/passwd admin '${MQTT_ADMIN_PASS}'
      "
    chmod 600 "$MQTT_PASSWD_FILE"

    success "MQTT admin credentials generated, passwd file updated, and appended to .env"
else
    success "MQTT admin credentials present"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# Step 2: Apply new database migrations
# ═══════════════════════════════════════════════════════════════════════════════
step "2/4 — Applying New Migrations"

MIGRATION_DIR="supabase/migrations"
APPLIED=0
SKIPPED=0
FAILED=0

# Check if the _migrations tracking table exists
HAS_TRACKING=$(docker compose exec -T db psql -U postgres -d postgres -tAc \
    "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='_migrations'" 2>/dev/null || echo "")

if [ "$HAS_TRACKING" = "1" ]; then
    # Use tracking table: only apply migrations not yet recorded
    for f in "$MIGRATION_DIR"/*.sql; do
        fname=$(basename "$f")

        ALREADY=$(docker compose exec -T db psql -U postgres -d postgres -tAc \
            "SELECT 1 FROM public._migrations WHERE name = '${fname}'" 2>/dev/null || echo "")

        if [ "$ALREADY" = "1" ]; then
            SKIPPED=$((SKIPPED + 1))
            continue
        fi

        echo -ne "  Applying ${fname}... "
        if docker compose exec -T db psql -U postgres -d postgres < "$f" > /tmp/migration_out.txt 2>&1; then
            # Record as applied
            docker compose exec -T db psql -U postgres -d postgres -c \
                "INSERT INTO public._migrations (name) VALUES ('${fname}') ON CONFLICT DO NOTHING" >/dev/null 2>&1
            echo -e "${GREEN}✔${NC}"
            APPLIED=$((APPLIED + 1))
        else
            echo -e "${RED}✖${NC}"
            echo -e "  ${DIM}$(cat /tmp/migration_out.txt | head -5)${NC}"
            FAILED=$((FAILED + 1))
        fi
    done
else
    # No tracking table yet — fall back to apply-all (setup.sh style)
    warn "Migration tracking table not found. Applying all migrations (errors = already applied)."
    echo
    for f in "$MIGRATION_DIR"/*.sql; do
        fname=$(basename "$f")
        if docker compose exec -T db psql -U postgres -d postgres < "$f" > /dev/null 2>&1; then
            success "$fname"
            APPLIED=$((APPLIED + 1))
        else
            echo -e "  ${YELLOW}⊘${NC} ${fname} ${DIM}(already applied or had errors)${NC}"
            SKIPPED=$((SKIPPED + 1))
        fi
    done
fi

echo
if [ "$FAILED" -gt 0 ]; then
    warn "Migrations: ${APPLIED} applied, ${SKIPPED} skipped, ${RED}${FAILED} failed${NC}"
else
    success "Migrations: ${APPLIED} applied, ${SKIPPED} skipped"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# Step 3: Rebuild & restart services
# ═══════════════════════════════════════════════════════════════════════════════
step "3/4 — Rebuilding Services"

# ── Detect which components changed ──────────────────────────────────────────
FRONTEND_CHANGED=false
FORWARDER_CHANGED=false

if [ "$BEFORE" != "$AFTER" ]; then
    CHANGED_FILES=$(cd "$SCRIPT_DIR/.." && git diff --name-only "${BEFORE}" "${AFTER}" 2>/dev/null || echo "")

    if echo "$CHANGED_FILES" | grep -q "^management-frontend/"; then
        FRONTEND_CHANGED=true
    fi
    if echo "$CHANGED_FILES" | grep -q "^Docker/mqtt/forwarder/"; then
        FORWARDER_CHANGED=true
    fi
fi

# ── Frontend ─────────────────────────────────────────────────────────────────
if [ "$SKIP_FRONTEND" = true ]; then
    if [ "$FRONTEND_CHANGED" = true ]; then
        warn "Frontend has changes but rebuild skipped (--no-frontend). Rebuild later with: docker compose build --no-cache frontend"
    else
        info "Frontend rebuild skipped (--no-frontend)"
    fi
elif [ "$FRONTEND_CHANGED" = true ]; then
    info "Frontend files changed — rebuilding..."
    docker compose build --no-cache frontend
    success "Frontend image built"
else
    info "No frontend changes — skipping rebuild"
fi

# ── Forwarder ────────────────────────────────────────────────────────────────
if [ "$FORWARDER_CHANGED" = true ]; then
    info "Forwarder files changed — rebuilding..."
    docker compose build forwarder
    success "Forwarder image built"
else
    info "No forwarder changes — skipping rebuild"
fi

# ── Restart services ─────────────────────────────────────────────────────────
# Note: broker is NOT recreated here to preserve persistent MQTT sessions and avoid
# race conditions (devices send "online" status before forwarder reconnects).
# To restart the broker, run: docker compose restart broker
RESTART_SERVICES="functions"

if [ "$FRONTEND_CHANGED" = true ] && [ "$SKIP_FRONTEND" = false ]; then
    RESTART_SERVICES="$RESTART_SERVICES frontend"
fi
if [ "$FORWARDER_CHANGED" = true ]; then
    RESTART_SERVICES="$RESTART_SERVICES forwarder"
fi

info "Restarting: ${RESTART_SERVICES}..."
docker compose up -d --no-deps --force-recreate $RESTART_SERVICES

success "All services restarted"

# ═══════════════════════════════════════════════════════════════════════════════
# Step 4: Health check
# ═══════════════════════════════════════════════════════════════════════════════
step "4/4 — Health Check"

sleep 3

# Check frontend
if docker compose ps frontend | grep -q "Up\|running"; then
    success "Frontend is running"
else
    warn "Frontend may not be healthy — check: docker compose logs frontend"
fi

# Check functions
if docker compose ps functions | grep -q "Up\|running"; then
    success "Edge functions are running"
else
    warn "Edge functions may not be healthy — check: docker compose logs functions"
fi

echo
docker compose ps
echo
success "Update complete!"
