
  create table "public"."embeddeds" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "owner_id" uuid default auth.uid(),
    "subdomain" bigint generated by default as identity not null,
    "mac_address" text,
    "status" text not null default 'offline'::text,
    "status_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "passkey" text not null default SUBSTRING(md5((random())::text) FROM 1 FOR 18)
      );



  create table "public"."sales" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "owner_id" uuid default auth.uid(),
    "embedded_id" uuid not null,
    "item_price" double precision not null default '0'::double precision,
    "item_number" bigint not null default '0'::bigint,
    "channel" text not null,
    "lat" double precision,
    "lng" double precision
      );


CREATE UNIQUE INDEX embeddeds_id_key ON public.embeddeds USING btree (id);

CREATE UNIQUE INDEX embeddeds_pkey ON public.embeddeds USING btree (id);

CREATE UNIQUE INDEX sales_id_key ON public.sales USING btree (id);

CREATE UNIQUE INDEX sales_pkey ON public.sales USING btree (id);

alter table "public"."embeddeds" add constraint "embeddeds_pkey" PRIMARY KEY using index "embeddeds_pkey";

alter table "public"."sales" add constraint "sales_pkey" PRIMARY KEY using index "sales_pkey";

alter table "public"."embeddeds" add constraint "embeddeds_id_key" UNIQUE using index "embeddeds_id_key";

alter table "public"."sales" add constraint "sales_embedded_id_fkey" FOREIGN KEY (embedded_id) REFERENCES public.embeddeds(id) not valid;

alter table "public"."sales" validate constraint "sales_embedded_id_fkey";

alter table "public"."sales" add constraint "sales_id_key" UNIQUE using index "sales_id_key";

grant delete on table "public"."embeddeds" to "anon";

grant insert on table "public"."embeddeds" to "anon";

grant references on table "public"."embeddeds" to "anon";

grant select on table "public"."embeddeds" to "anon";

grant trigger on table "public"."embeddeds" to "anon";

grant truncate on table "public"."embeddeds" to "anon";

grant update on table "public"."embeddeds" to "anon";

grant delete on table "public"."embeddeds" to "authenticated";

grant insert on table "public"."embeddeds" to "authenticated";

grant references on table "public"."embeddeds" to "authenticated";

grant select on table "public"."embeddeds" to "authenticated";

grant trigger on table "public"."embeddeds" to "authenticated";

grant truncate on table "public"."embeddeds" to "authenticated";

grant update on table "public"."embeddeds" to "authenticated";

grant delete on table "public"."embeddeds" to "postgres";

grant insert on table "public"."embeddeds" to "postgres";

grant references on table "public"."embeddeds" to "postgres";

grant select on table "public"."embeddeds" to "postgres";

grant trigger on table "public"."embeddeds" to "postgres";

grant truncate on table "public"."embeddeds" to "postgres";

grant update on table "public"."embeddeds" to "postgres";

grant delete on table "public"."embeddeds" to "service_role";

grant insert on table "public"."embeddeds" to "service_role";

grant references on table "public"."embeddeds" to "service_role";

grant select on table "public"."embeddeds" to "service_role";

grant trigger on table "public"."embeddeds" to "service_role";

grant truncate on table "public"."embeddeds" to "service_role";

grant update on table "public"."embeddeds" to "service_role";

grant delete on table "public"."sales" to "anon";

grant insert on table "public"."sales" to "anon";

grant references on table "public"."sales" to "anon";

grant select on table "public"."sales" to "anon";

grant trigger on table "public"."sales" to "anon";

grant truncate on table "public"."sales" to "anon";

grant update on table "public"."sales" to "anon";

grant delete on table "public"."sales" to "authenticated";

grant insert on table "public"."sales" to "authenticated";

grant references on table "public"."sales" to "authenticated";

grant select on table "public"."sales" to "authenticated";

grant trigger on table "public"."sales" to "authenticated";

grant truncate on table "public"."sales" to "authenticated";

grant update on table "public"."sales" to "authenticated";

grant delete on table "public"."sales" to "postgres";

grant insert on table "public"."sales" to "postgres";

grant references on table "public"."sales" to "postgres";

grant select on table "public"."sales" to "postgres";

grant trigger on table "public"."sales" to "postgres";

grant truncate on table "public"."sales" to "postgres";

grant update on table "public"."sales" to "postgres";

grant delete on table "public"."sales" to "service_role";

grant insert on table "public"."sales" to "service_role";

grant references on table "public"."sales" to "service_role";

grant select on table "public"."sales" to "service_role";

grant trigger on table "public"."sales" to "service_role";

grant truncate on table "public"."sales" to "service_role";

grant update on table "public"."sales" to "service_role";


