-- public.embeddeds definition

-- Drop table

-- DROP TABLE public.embeddeds;

CREATE TABLE public.embeddeds (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	owner_id uuid DEFAULT auth.uid() NULL,
	subdomain int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	mac_address text NULL,
	"status" text DEFAULT 'offline' NOT NULL,
	status_at timestamptz DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
	passkey text DEFAULT SUBSTRING(md5(random()::text) FROM 1 FOR 18) NOT NULL
);

-- public.sales definition

-- Drop table

-- DROP TABLE public.sales;

CREATE TABLE public.sales (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	owner_id uuid DEFAULT auth.uid() NULL,
	embedded_id uuid NOT NULL,
	item_price float8 DEFAULT '0'::double precision NOT NULL,
	item_number int8 DEFAULT '0'::bigint NOT NULL,
	channel text NOT NULL,
	lat float8 NULL,
	lng float8 NULL
);
