/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { NetworkOnly } from 'workbox-strategies'

declare let self: ServiceWorkerGlobalScope

// Precache all assets generated by the build (includes /offline.html)
precacheAndRoute(self.__WB_MANIFEST)

// ─── Offline fallback for navigation requests ────────────────────────────────
const navigationHandler = new NetworkOnly()
const navigationRoute = new NavigationRoute(navigationHandler, {
  // Let the network handle navigation; if it fails, serve offline.html
})

navigationRoute.setCatchHandler(async () => {
  const cache = await caches.open('workbox-precache-v2')
  const keys = await cache.keys()
  // Find the precached offline.html (workbox appends a revision hash to the key)
  const offlineKey = keys.find((k) => new URL(k.url).pathname.endsWith('/offline.html'))
  if (offlineKey) {
    const response = await cache.match(offlineKey)
    if (response) return response
  }
  return Response.error()
})

registerRoute(navigationRoute)

// ─── SKIP_WAITING message handler (for app update flow) ─────────────────────
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// ─── Push notification handler ──────────────────────────────────────────────
self.addEventListener('push', (event) => {
  if (!event.data) return

  let payload: { title?: string; body?: string; icon?: string; image?: string; data?: Record<string, unknown> }
  try {
    payload = event.data.json()
  } catch {
    payload = { title: 'VMflow', body: event.data.text() }
  }

  const title = payload.title ?? 'VMflow'
  const options: NotificationOptions = {
    body: payload.body ?? '',
    icon: payload.image ?? payload.icon ?? '/icons/icon-192x192.png',
    badge: '/icons/icon-192x192.png',
    image: payload.image,
    data: payload.data ?? {},
    tag: payload.data?.type ? String(payload.data.type) : undefined,
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

// ─── Notification click handler ─────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const data = event.notification.data as Record<string, unknown> | undefined

  // Determine target URL based on notification type
  let targetUrl = '/'
  if (data?.type === 'sale' && data?.embedded_id) {
    // Navigate to the machine that made the sale
    targetUrl = `/machines`
  } else if (data?.type === 'low_stock' && data?.machine_id) {
    targetUrl = `/machines/${data.machine_id}`
  }

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Try to focus an existing window
      for (const client of clientList) {
        if (new URL(client.url).origin === self.location.origin && 'focus' in client) {
          client.focus()
          client.navigate(targetUrl)
          return
        }
      }
      // Otherwise open a new window
      return self.clients.openWindow(targetUrl)
    }),
  )
})
